### ISSUE TITLE
Duplicity fails with CertificateError when backing up to Amazon S3

### ISSUE THREAD

**Issue by sebastianhutter** [camptocamp/conplicity#119]
When running conplicity every backup fails with a certificate error. It seems like duplicity receives a wrong URL.

Command executed:
`docker run -v /var/run/docker.sock:/var/run/docker.sock:ro  --rm -ti \
   -e CONPLICITY_LOG_LEVEL=debug \
   -e CONPLICITY_TARGET_URL="s3+http://s3.eu-central-1.amazonaws.com/mytestbackups3bucket/backup" \
   -e AWS_ACCESS_KEY_ID="myid" \
   -e AWS_SECRET_ACCESS_KEY="mykey" \
     camptocamp/conplicity`

The backup fails for every container with the following message:
`
```
  DEBU[0000] Creating container                            binds="rancher-agent-state:/var/lib/docker/volumes/rancher-agent-state/_data:ro, duplicity_cache:/root/.cache/duplicity" command="--full-if-older-than 15D --s3-use-new-style --ssh-options -oStrictHostKeyChecking=no --no-encryption --allow-source-mismatch --n
ame rancher-agent-state /var/lib/docker/volumes/rancher-agent-state/_data/ s3+http://s3.eu-central-1.amazonaws.com/mytestbackups3bucket/backup" environment="AWS_ACCESS_KEY_ID=myid, AWS_SECRET_ACCESS_KEY=mykey, SWIFT_USERNAME
=, SWIFT_PASSWORD=, SWIFT_AUTHURL=, SWIFT_TENANTNAME=, SWIFT_REGIONNAME=, SWIFT_AUTHVERSION=2" image="camptocamp/duplicity:latest"
DEBU[0000] Launching 'duplicity --full-if-older-than 15D --s3-use-new-style --ssh-options -oStrictHostKeyChecking=no --no-encryption --allow-source-mismatch --name rancher-agent-state /var/lib/docker/volumes/rancher-agent-state/_data/ s3+http://s3.eu-central-1.amazonaws.com/mytestbackups3bucket/backup/rancher-agent-state'...
DEBU[0002]  Traceback (most recent call last):
   File "/usr/bin/duplicity", line 1546, in <module>
     with_tempdir(main)
   File "/usr/bin/duplicity", line 1540, in with_tempdir
     fn()
   File "/usr/bin/duplicity", line 1375, in main
     action = commandline.ProcessCommandLine(sys.argv[1:])
   File "/usr/lib/python2.7/dist-packages/duplicity/commandline.py", line 1126, in ProcessCommandLine
     backup, local_pathname = set_backend(args[0], args[1])
   File "/usr/lib/python2.7/dist-packages/duplicity/commandline.py", line 1015, in set_backend
     globals.backend = backend.get_backend(bend)
   File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 223, in get_backend
     obj = get_backend_object(url_string)
   File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 209, in get_backend_object
     return factory(pu)
   File "/usr/lib/python2.7/dist-packages/duplicity/backends/_boto_single.py", line 166, in __init__
     self.resetConnection()
   File "/usr/lib/python2.7/dist-packages/duplicity/backends/_boto_single.py", line 191, in resetConnection
     location=self.my_location)
   File "/usr/lib/python2.7/dist-packages/boto/s3/connection.py", line 612, in create_bucket
     data=data)
   File "/usr/lib/python2.7/dist-packages/boto/s3/connection.py", line 664, in make_request
     retry_handler=retry_handler
   File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
     retry_handler=retry_handler)
   File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 943, in _mexe
     request.body, request.headers)
   File "/usr/lib/python2.7/httplib.py", line 1057, in request
     self._send_request(method, url, body, headers)
   File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
     self.endheaders(body)
   File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
     self._send_output(message_body)
   File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
     self.send(msg)
   File "/usr/lib/python2.7/httplib.py", line 859, in send
     self.connect()
   File "/usr/lib/python2.7/httplib.py", line 1278, in connect
     server_hostname=server_hostname)
   File "/usr/lib/python2.7/ssl.py", line 353, in wrap_socket
     _context=self)
   File "/usr/lib/python2.7/ssl.py", line 601, in __init__
     self.do_handshake()
   File "/usr/lib/python2.7/ssl.py", line 838, in do_handshake
     match_hostname(self.getpeercert(), self.server_hostname)
   File "/usr/lib/python2.7/ssl.py", line 272, in match_hostname
     % (hostname, ', '.join(map(repr, dnsnames))))
 CertificateError: hostname 's3.eu-central-1.amazonaws.com.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'


DEBU[0002] Removing container                            container=56284b6cfdb7cc3f6b14971327ac2a4ed3242d8039561d3702f413c1ea9eb05b
DEBU[0002] Adding event                                  event="conplicity_backupExitCode{} 30" metric="conplicity_backupExitCode
```

To me it looks like the conplicity passes a partially hardcoded url to the duplicity container.
`
CertificateError: hostname 's3.eu-central-1.amazonaws.com.**s3.amazonaws.com**' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'.
`

I am runnig docker engine 1.1.3.0 and camptocamp/conplicity:latest (be5a00ba8163) with camptocamp/duplicity:latest (f290ec85b0e5).

**Comment by mcanevet** [comment]
Could you please test on `eu-west-1`? We  also had some troubles with `eu-central-1`. I suspect the `duplicity` version we are using to not be compatible with this region.

**Comment by sebastianhutter** [comment]
Created a new bucket in eu-west-1 (ireleand) but receive the same CertificateError
```
docker run -v /var/run/docker.sock:/var/run/docker.sock:ro --rm -ti \ 
  -e CONPLICITY_LOG_LEVEL=debug \ 
  -e CONPLICITY_TARGET_URL="s3+http://s3-eu-west-1.amazonaws.com/mytestbackups3bucket/backup" \ 
  -e AWS_ACCESS_KEY_ID="myid" \ 
  -e AWS_SECRET_ACCESS_KEY="mykey" \ 
  camptocamp/conplicity
```

```
DEBU[0004]  Traceback (most recent call last):
   File "/usr/bin/duplicity", line 1546, in <module>
     with_tempdir(main)
   File "/usr/bin/duplicity", line 1540, in with_tempdir
     fn()
   File "/usr/bin/duplicity", line 1375, in main
     action = commandline.ProcessCommandLine(sys.argv[1:])
   File "/usr/lib/python2.7/dist-packages/duplicity/commandline.py", line 1118, in ProcessCommandLine
     globals.backend = backend.get_backend(args[0])
   File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 223, in get_backend
     obj = get_backend_object(url_string)
   File "/usr/lib/python2.7/dist-packages/duplicity/backend.py", line 209, in get_backend_object
     return factory(pu)
   File "/usr/lib/python2.7/dist-packages/duplicity/backends/_boto_single.py", line 166, in __init__
     self.resetConnection()
   File "/usr/lib/python2.7/dist-packages/duplicity/backends/_boto_single.py", line 191, in resetConnection
     location=self.my_location)
   File "/usr/lib/python2.7/dist-packages/boto/s3/connection.py", line 612, in create_bucket
     data=data)
   File "/usr/lib/python2.7/dist-packages/boto/s3/connection.py", line 664, in make_request
     retry_handler=retry_handler
   File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 1071, in make_request
     retry_handler=retry_handler)
   File "/usr/lib/python2.7/dist-packages/boto/connection.py", line 943, in _mexe
     request.body, request.headers)
   File "/usr/lib/python2.7/httplib.py", line 1057, in request
     self._send_request(method, url, body, headers)
   File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
     self.endheaders(body)
   File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
     self._send_output(message_body)
   File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
     self.send(msg)
   File "/usr/lib/python2.7/httplib.py", line 859, in send
     self.connect()
   File "/usr/lib/python2.7/httplib.py", line 1278, in connect
     server_hostname=server_hostname)
   File "/usr/lib/python2.7/ssl.py", line 353, in wrap_socket
     _context=self)
   File "/usr/lib/python2.7/ssl.py", line 601, in __init__
     self.do_handshake()
   File "/usr/lib/python2.7/ssl.py", line 838, in do_handshake
     match_hostname(self.getpeercert(), self.server_hostname)
   File "/usr/lib/python2.7/ssl.py", line 272, in match_hostname
     % (hostname, ', '.join(map(repr, dnsnames))))
 CertificateError: hostname 's3-eu-west-1.amazonaws.com.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'
```

**Comment by sebastianhutter** [comment]
I just ran the command with `s3://` instead of `s3+http`. 
This works for buckets in the region eu-west-1 and eu-central-1.

```
docker run -v /var/run/docker.sock:/var/run/docker.sock:ro --rm -ti \ 
  -e CONPLICITY_LOG_LEVEL=debug \ 
  -e CONPLICITY_TARGET_URL="s3://s3-eu-west-1.amazonaws.com/mytestbackups3bucket/backup" \ 
  -e AWS_ACCESS_KEY_ID="myid" \ 
  -e AWS_SECRET_ACCESS_KEY="mykey" \ 
  camptocamp/conplicity
```

**Comment by mcanevet** [comment]
Great! I close this then.
